// ChouLegal central account project.
window.SUPABASE_URL = 'https://brbznudnufaeptdpyvib.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJicmJ6bnVkbnVmYWVwdGRweXZpYiIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc2OTQzODA5LCJleHAiOjIwOTI1MTk4MDl9.wVLRVnHwlQUsMxhfDs1jua2bJvSrv0xa7WKP5Y4RRsE';
