// 共用周全法律科技 ChouLegal Supabase 專案（與 InheritancePro 同帳號系統）
window.SUPABASE_URL = 'https://nayqgpvwxzourigvjqxj.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5heXFncHZ3eHpvdXJpZ3ZqcXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MDAwMzYsImV4cCI6MjA5MDE3NjAzNn0.KmrFOUhIz8exLoguMkSa4azHagsXilkHDHQXt5gBkik';
